<?php

namespace abdulkadiragoliya\contentintelligence\services\audit\rules;

use craft\elements\Entry;
use abdulkadiragoliya\contentintelligence\models\AuditResult;
use abdulkadiragoliya\contentintelligence\services\audit\BaseAuditRule;

/**
 * Checks heading hierarchy (H1, H2, H3) inside rich text and entry content.
 */
class HeadingStructureRule extends BaseAuditRule
{
    public function getId(): string
    {
        return 'heading_structure';
    }

    public function getName(): string
    {
        return 'Heading Hierarchy & Structure';
    }

    public function run(Entry $entry): ?AuditResult
    {
        $html = $this->extractRawHtml($entry);

        if (empty($html)) {
            return null; // No rich-text formatting present to inspect
        }

        preg_match_all('/<h([1-6])[^>]*>(.*?)<\/h\1>/is', $html, $matches);
        $headingLevels = $matches[1] ?? [];

        if (empty($headingLevels)) {
            return $this->createResult(
                AuditResult::SEVERITY_NOTICE,
                'No Subheadings Found',
                'This entry has formatted text but does not use subheadings (H2, H3) to organize sections.',
                'Break long text into digestible sections with descriptive subheadings.'
            );
        }

        $h1Count = count(array_filter($headingLevels, fn($l) => $l === '1'));
        if ($h1Count > 1) {
            return $this->createResult(
                AuditResult::SEVERITY_WARNING,
                'Multiple H1 Tags Detected in Body',
                "Found {$h1Count} <h1> tags inside the entry fields. Typically pages should have a single <h1> generated by the template title.",
                'Convert secondary <h1> headings into <h2> subheadings.',
                ['h1Count' => $h1Count]
            );
        }

        // Check for skipped heading levels (e.g. H2 -> H4 without H3)
        $previousLevel = 1;
        $skipped = false;
        foreach ($headingLevels as $level) {
            $currentLevel = (int)$level;
            if ($currentLevel > $previousLevel + 1) {
                $skipped = true;
                break;
            }
            $previousLevel = $currentLevel;
        }

        if ($skipped) {
            return $this->createResult(
                AuditResult::SEVERITY_WARNING,
                'Skipped Heading Hierarchy Level',
                'Heading levels are skipped (e.g. H2 followed directly by H4 without an intervening H3).',
                'Maintain a sequential heading hierarchy to help readers and assistive technology navigate.',
                ['levels' => $headingLevels]
            );
        }

        return $this->createResult(
            AuditResult::SEVERITY_GOOD,
            'Healthy Heading Structure',
            'Subheadings follow a clean logical sequence.',
            'No action needed.',
            ['levels' => $headingLevels]
        );
    }
}
